openapi: 3.0.3
info:
  title: Ecom-Api-Service - OpenAPI 3.0
  description: |-
    Ecom Api Service
  version: 0.1.0
  contact:
    name: API Support
    email: work.mitakshar@gmail.com
servers:
  - url: http://localhost:5454
tags:
  - name: ecomApi V1 - Administrator  Controller
    description: Admin Endpoints version 1
paths:
  /v1/admin/orders/placeOrder/{orderId}:
    put:
      tags:
        - ecomApi V1 Admin-Controller
      summary: "Place Order"
      operationId: "placeOrderHandler"
      parameters:
        - name: "orderId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "./ecomApiComponents.yaml#/components/schemas/BasicOrderResponse"
        '422':
          description: "Order Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'

  /v1/admin/orders/confirm/{orderId}:
    put:
      tags:
        - ecomApi V1 Admin-Controller
      summary: "Confirm Order"
      operationId: "confirmOrderHandler"
      parameters:
        - name: "orderId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "./ecomApiComponents.yaml#/components/schemas/BasicOrderResponse"
        '422':
          description: "Order Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'

  /v1/admin/orders/ship/{orderId}:
    put:
      tags:
        - ecomApi V1 Admin-Controller
      summary: "Ship Order"
      operationId: "shipOrderHandler"
      parameters:
        - name: "orderId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "./ecomApiComponents.yaml#/components/schemas/BasicOrderResponse"
        '422':
          description: "Order Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'

  /v1/admin/orders/cancel/{orderId}:
    put:
      tags:
        - ecomApi V1 Admin-Controller
      summary: "Cancel Order"
      operationId: "cancelOrderHandler"
      parameters:
        - name: "orderId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "./ecomApiComponents.yaml#/components/schemas/BasicOrderResponse"
        '422':
          description: "Order Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'

  /v1/admin/orders/deliver/{orderId}:
    put:
      tags:
        - ecomApi V1 Admin-Controller
      summary: "Deliver Order"
      operationId: "deliverOrderHandler"
      parameters:
        - name: "orderId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "./ecomApiComponents.yaml#/components/schemas/BasicOrderResponse"
        '422':
          description: "Order Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'

  /v1/admin/users:
    get:
      tags:
        - ecomApi V1 Admin-Controller
      summary: "Get All Users"
      operationId: "findAllUsersHandler"
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "./ecomApiComponents.yaml#/components/schemas/AllUserResponse"
        '422':
          description: "Order Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'

  /v1/admin/product/create:
    post:
      tags:
        - ecomApi V1 Admin-Controller
      summary: "Create Products"
      operationId: "createProductHandler"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./ecomApiComponents.yaml#/components/schemas/CreateProductRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "./ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse"
        '422':
          description: "Product Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'

  /v1/admin/product/update:
    put:
      tags:
        - ecomApi V1 Admin-Controller
      summary: "Update Product"
      operationId: "updateProductHandler"
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./ecomApiComponents.yaml#/components/schemas/updateProductRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "./ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse"
        '422':
          description: "Product Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'

  /v1/admin/product/allProducts:
    get:
      tags:
        - ecomApi V1 Admin-Controller
      summary: "Get All Products"
      operationId: "findAllProductHandler"
      parameters:
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "./ecomApiComponents.yaml#/components/schemas/AllProductResponse"
        '422':
          description: "Product Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './ecomApiComponents.yaml#/components/schemas/EcomApiServiceBaseApiResponse'
